#!/usr/bin/env python3
"""
paper/make_tables.py - Build every table, figure and in-text number of the
paper from the analysis output. No API calls, stdlib only. Nothing is typed
by hand: all numbers come from the files below.

    python3 analysis.py --extra clean=clean_fable.csv --extra blind=blind_fable.csv \
        --extra para=para_fable.csv --extra gpt4=gpt4_p1.csv \
        --cutoff gpt4=2021-09-30 --csv results.csv > results.txt
    (and the variants in paper/runs/, see paper/README.md)
    python3 paper/extra_checks.py
    python3 paper/make_tables.py

Reads   results.txt, results.csv (default run), paper/runs/{strict,all,
        matched,raw,p1}.{txt,csv}, paper/runs/extra.csv, paper/runs/extra.txt,
        paper/runs/scatter.csv, and the data files (corpus_types.csv,
        probe_*.csv, score files, surprises.csv, yields.csv).
Writes  paper/tables/*.tex, paper/figures/*.tex and paper/tables/numbers.tex.
        numbers.tex defines \\R{key} for every number quoted in the text; an
        unknown key prints ??key?? in bold so it cannot go unnoticed.
"""

import csv
import os
import re
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, ROOT)

TAB = os.path.join("paper", "tables")
FIG = os.path.join("paper", "figures")
RUNS = os.path.join("paper", "runs")
V = {}          # key -> formatted string, written to numbers.tex
SD = {}         # hold-meeting standard deviations of the outcomes
GZ = []         # part G bootstrap gaps (z, interval excludes 0)


# --- helpers -------------------------------------------------------------------

def tex(s):
    """Escape plain text for LaTeX."""
    rep = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
           "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\^{}"}
    s = "".join(rep.get(c, c) for c in s)
    s = s.replace("—", "---").replace("–", "--").replace("’", "'").replace("“", "``").replace("”", "''")
    s = re.sub(r'"([^"]*)"', r"``\1''", s)
    return s.replace('"', "''")


def f(x, d=2, sign=False):
    if x is None or x != x:
        return "--"
    s = f"{x:+.{d}f}" if sign else f"{x:.{d}f}"
    return s.replace("-", "$-$") if s.startswith("-") else s


def fp(p):
    return "$<$0.001" if p < 0.001 else f(p, 3)


def put(key, val):
    if key in V and V[key] != val:
        raise SystemExit(f"numbers.tex: key {key} set twice ({V[key]} vs {val})")
    V[key] = val


def write(name, body):
    os.makedirs(TAB, exist_ok=True)
    with open(os.path.join(TAB, name), "w") as fh:
        fh.write("% generated by paper/make_tables.py - do not edit\n" + body)


def section(txt, letter):
    """The block of analysis.py output for part <letter>."""
    m = re.search(rf"^{letter}\. .*?$(.*?)(?=^=+\n^[A-Z]+[\. ]|\Z)", txt, re.S | re.M)
    if not m:
        raise SystemExit(f"part {letter} not found")
    return m.group(1)


def load_rows(path):
    out = []
    for r in csv.DictReader(open(path)):
        for k in ("beta", "t_ols", "t_hc1", "t_nw", "p_nw", "r2"):
            r[k] = float(r[k]) if r.get(k) not in (None, "") else float("nan")
        r["p_holm"] = float(r["p_holm"]) if r.get("p_holm") else None
        r["n"] = int(r["n"])
        out.append(r)
    return out


def pick(rows, part, model, y, sample, control="-"):
    hits = [r for r in rows if r["part"] == part and r["model"] == model and r["y"] == y
            and r["sample"] == sample and r["control"] == control]
    if len(hits) != 1:
        raise SystemExit(f"{len(hits)} rows for {part} {model} {y} {sample} {control}")
    return hits[0]


TXT = open("results.txt").read()
ROWS = load_rows("results.csv")
VAR = {k: (open(os.path.join(RUNS, k + ".txt")).read(), load_rows(os.path.join(RUNS, k + ".csv")))
       for k in ("strict", "all", "matched", "raw", "p1")}
MODELNAME = {"gemini-2.5-flash": "Gemini 2.5 Flash", "claude-3-haiku": "Claude 3 Haiku",
             "gpt-4o-mini": "GPT-4o mini", "claude-fable-5.1": "Claude Fable 5.1"}


# --- corpus and data ---------------------------------------------------------------

def corpus():
    types = list(csv.DictReader(open("corpus_types.csv")))
    cnt = {}
    for r in types:
        cnt[r["type"]] = cnt.get(r["type"], 0) + 1
    put("corpus.files", str(len(types)))
    for k, v in cnt.items():
        put("corpus." + k.replace("_", ""), str(v))
    put("corpus.policy", str(len(types) - cnt["notice"]))
    put("corpus.first", types[0]["date"])
    put("corpus.last", types[-1]["date"])
    m = re.search(r"--corpus policy: (\d+) statements", TXT)
    put("corpus.policy.check", m.group(1))
    months = {}
    for r in types:
        if r["date"] < "2024":
            months[r["date"][:7]] = months.get(r["date"][:7], 0) + 1
    put("corpus.multimonth", str(sum(v > 1 for v in months.values())))
    put("corpus.prenotices", str(sum(r["type"] == "notice" and r["date"] < "2024" for r in types)))
    put("corpus.zlbnotices", str(sum(r["type"] == "notice" and "2009-01" <= r["date"][:7] <= "2015-11"
                                     for r in types)))
    lines = []
    for r in types:
        if r["type"] == "scheduled":
            continue
        note = (r["note"].replace("not in surprises.csv", "no MPS in the Bauer--Swanson data")
                .replace("TSLF", "Term Securities Lending Facility")
                .replace("FIMA repo", "repo facility for foreign and international monetary authorities")
                .replace("9/11", "11 September 2001"))
        lines.append(f"{r['date']} & {tex(r['type'].replace('_', ' '))} & {tex(note).replace('Bauer--Swanson', 'Bauer--Swanson')} \\\\")
    write("tab_corpus.tex", "\\begin{tabular}{@{}llp{9cm}@{}}\n\\toprule\nDate & Type & Note \\\\\n\\midrule\n"
          + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")


def descriptives():
    import analysis as A
    statements, policy, market = A.load_market()
    statements, _ = A.corpus_filter(statements, "policy")
    pre = [d for d in statements if d < A.POST_CUTOFF]
    hold = [d for d in pre[1:] if policy[d] == 0]
    put("desc.pre", str(len(pre)))
    put("desc.prepairs", str(len(pre) - 1))
    put("desc.hold", str(len(hold)))
    put("desc.moves", str(sum(policy[d] != 0 for d in pre)))
    put("desc.post", str(sum(d >= A.POST_CUTOFF for d in statements)))
    # prompt coverage per policy statement
    for lab, path in (("fable", A.FABLE), ("gemini", A.GEMINI)):
        sc = A.collapse(A.load_cells(path)[0])
        k = [len(sc.get(d, {})) for d in statements]
        put(f"cover.{lab}.five", str(sum(x == 5 for x in k)))
        put(f"cover.{lab}.fewer", str(sum(0 < x < 5 for x in k)))
        put(f"cover.{lab}.none", str(sum(x == 0 for x in k)))
        put(f"cover.{lab}.prefive", str(sum(x == 5 for x, d in zip(k, statements) if d < A.POST_CUTOFF)))
        put(f"cover.{lab}.prefewer", str(sum(0 < x < 5 for x, d in zip(k, statements) if d < A.POST_CUTOFF)))
        few = [d for x, d in zip(k, statements) if 0 < x < 5]
        if few:
            put(f"cover.{lab}.fewfirst", min(few)[:4])
    rows = []
    for y, lab, unit in (("MPS", "MPS", "pp"), ("MPS_ORTH", "MPS\\_ORTH", "pp"),
                         ("t2", "2-year yield, 30-minute ($t_2$)", "bp"),
                         ("t10", "10-year yield, 30-minute ($t_{10}$)", "bp"),
                         ("d2", "2-year yield, daily ($d_2$)", "bp"),
                         ("d10", "10-year yield, daily ($d_{10}$)", "bp")):
        for samp, use in (("all", pre[1:]), ("hold", hold)):
            v = [market[d][y] for d in use if y in market[d]]
            rows.append((lab if samp == "all" else "", unit, samp, len(v),
                         statistics.mean(v), statistics.stdev(v), min(v), max(v),
                         min(d for d in use if y in market[d])[:4],
                         max(d for d in use if y in market[d])[:4]))
            if samp == "hold":
                put(f"desc.sd.{y}", f(statistics.stdev(v), 3 if y.startswith("MPS") else 1))
                SD[y] = statistics.stdev(v)
                put(f"desc.n.{y}", str(len(v)))
    for a, b in (("t2", "d2"), ("t10", "d10")):
        both = [d for d in pre[1:] if a in market[d] and b in market[d]]
        put(f"desc.corr.{a}.{b}", f(statistics.correlation([market[d][a] for d in both],
                                                          [market[d][b] for d in both])))
    for y in ("t2", "t10"):
        both = [d for d in hold if "MPS" in market[d] and y in market[d]]
        put(f"desc.corr.MPS.{y}", f(statistics.correlation([market[d]["MPS"] for d in both],
                                                            [market[d][y] for d in both])))
    d = 3
    body = ["\\begin{tabular}{@{}llrrrrrrl@{}}", "\\toprule",
            "Outcome & Unit & Sample & $n$ & Mean & SD & Min & Max & Years \\\\", "\\midrule"]
    for lab, unit, samp, n, mu, sd, lo, hi, a, b in rows:
        dd = 3 if unit == "pp" else 1
        body.append(f"{lab} & {unit if lab else ''} & {samp} & {n} & {f(mu, dd)} & {f(sd, dd)} & {f(lo, dd)} & {f(hi, dd)} & {a}--{b} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_desc.tex", "\n".join(body) + "\n")


# --- part A: reliability ---------------------------------------------------------

def reliability():
    sec = section(TXT, "A")
    pat = re.compile(r"^  (\S.*?) \[(.*?)\]\s+(\d+)\s+(\S+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+|nan)"
                     r"\s+([\d.]+)\s+(-?\d+)%", re.M)
    rows = pat.findall(sec)
    icc, alpha = rows[:len(rows) // 2], rows[len(rows) // 2:]
    assert len(icc) == len(alpha) == 7, len(rows)
    body = ["\\begin{tabular}{@{}llr ccccc ccccc@{}}", "\\toprule",
            " & & & \\multicolumn{5}{c}{ICC(3,1)} & \\multicolumn{5}{c}{Krippendorff's $\\alpha$} \\\\",
            "\\cmidrule(lr){4-8}\\cmidrule(l){9-13}",
            "Model & Window & $n$ & Raw & Resid & Hold & Chg & Drop & Raw & Resid & Hold & Chg & Drop \\\\",
            "\\midrule"]
    for i, (a, b) in enumerate(zip(icc, alpha)):
        name, path, n, win = a[0], a[1], a[2], a[3]
        win = win.replace("..", "--")
        label = MODELNAME.get(name, name)
        if i == 4:
            body.append("\\addlinespace")
        if i == 5:
            body.append("\\addlinespace\\multicolumn{13}{@{}l}{\\emph{Full corpus (statements with all five prompts)}}\\\\")
        body.append(f"{label} & {win} & {n} & " + " & ".join(a[4:8]) + f" & {a[8]}\\% & "
                    + " & ".join(b[4:8]) + f" & {b[8]}\\% \\\\")
        key = {"changes.csv": "gem", "changes_claude.csv": "haiku", "changes_openai.csv": "mini",
               "changes_frontier.csv": "fable", "changes_2004.csv": "gem04",
               "full_gemini.csv": "gemfull", "scores_fable.csv": "fablefull"}[path]
        for j, col in enumerate(("raw", "resid", "hold", "chg")):
            put(f"icc.{key}.{col}", a[4 + j])
            put(f"alpha.{key}.{col}", b[4 + j])
        put(f"icc.{key}.drop", a[8] + "\\%")
        put(f"alpha.{key}.drop", b[8] + "\\%")
        put(f"icc.{key}.n", n)
    body.insert(6, "\\multicolumn{13}{@{}l}{\\emph{Crossed block: same statements, five prompts, four models}}\\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_reliability.tex", "\n".join(body) + "\n")
    m = re.search(r"test-retest: (\d+) cells scored in two runs, r = ([\d.]+), mean \|diff\| = ([\d.]+), (\d+) differ", sec)
    put("retest.n", m.group(1))
    put("retest.r", m.group(2))
    put("retest.mad", m.group(3))
    put("retest.differ", m.group(4))
    # variance decomposition
    vp = re.compile(r"^  (levels|changes), (raw|std in model)\s+(\d+)\s+" + r"\s+".join([r"([\d.]+)%"] * 7), re.M)
    vrows = vp.findall(sec)
    assert len(vrows) == 4
    m = re.search(r"decomposition, (\d+) statements \((\S+)\) x (\d+) prompts x (\d+) models", sec)
    put("var.n", m.group(1))
    body = ["\\begin{tabular}{@{}llr rrrrrrr@{}}", "\\toprule",
            "Data & Scaling & $n$ & Statement & Prompt & Model & S$\\times$P & S$\\times$M & P$\\times$M & Residual \\\\",
            "\\midrule"]
    for kind, scale, n, *sh in vrows:
        body.append(f"{kind.capitalize()} & {'raw' if scale == 'raw' else 'std.\\ within model'} & {n} & "
                    + " & ".join(sh) + " \\\\")
        k = f"var.{kind}.{'raw' if scale == 'raw' else 'std'}"
        for nm, v in zip(("stmt", "prompt", "model", "sxp", "sxm", "pxm", "resid"), sh):
            put(f"{k}.{nm}", v + "\\%")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_variance.tex", "\n".join(body) + "\n")
    return icc


# --- part E + probes: recognition -------------------------------------------------

def probe_counts(path):
    rows = [r for r in csv.DictReader(open(path)) if r["err_months"] != ""]
    e = [abs(int(r["err_months"])) for r in rows]
    zlb = [abs(int(r["err_months"])) for r in rows if "2009-01" <= r["date"] <= "2015-11"]
    return {"n": len(e), "exact": sum(x == 0 for x in e), "w1": sum(x <= 1 for x in e),
            "w3": sum(x <= 3 for x in e), "zlbn": len(zlb), "zlb": sum(x == 0 for x in zlb),
            "high": sum(r["confidence"] == "high" for r in rows)}


def recognition():
    sec = section(TXT, "E")
    blind = probe_counts("probe_fable.csv")
    para = probe_counts("probe_para.csv")
    post = probe_counts("probe_post.csv")
    # cross-check against analysis.py's printout
    m = re.search(r"exact month\s+(\d+) / (\d+)", sec)
    assert (int(m.group(1)), int(m.group(2))) == (blind["exact"], blind["n"])
    m = re.search(r"ZLB 2009-15 exact\s+(\d+) / (\d+)", sec)
    assert (int(m.group(1)), int(m.group(2))) == (blind["zlb"], blind["zlbn"])
    base = {}
    for key, lab in (("w1", "within 1 month"), ("w3", "within 3 months"),
                     ("adj", "nearest = adjacent"), ("br", "2 nearest bracket it")):
        m = re.search(rf"{lab}\s+(\d+)/(\d+)\s+(\d+)/(\d+)", sec)
        base[key] = (int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)))
    pc = lambda a, b: f(100 * a / b, 0) + "\\%"
    for nm, d in (("blind", blind), ("para", para), ("post", post)):
        for k in ("n", "exact", "w1", "w3", "zlb", "zlbn", "high"):
            put(f"probe.{nm}.{k}", str(d[k]))
        put(f"probe.{nm}.exactpct", pc(d["exact"], d["n"]))
        put(f"probe.{nm}.w1pct", pc(d["w1"], d["n"]))
    put("base.w1", str(base["w1"][0]))
    put("base.w1pct", pc(base["w1"][0], base["w1"][1]))
    put("base.w3", str(base["w3"][0]))
    put("base.w3pct", pc(base["w3"][0], base["w3"][1]))
    put("base.adj", str(base["adj"][0]))
    put("base.br", str(base["br"][0]))
    put("base.brpct", pc(base["br"][0], base["br"][1]))
    put("base.zlb.br", str(base["br"][2]))
    put("base.zlb.w3", str(base["w3"][2]))
    put("base.n", str(base["w1"][1]))

    def cell(a, b):
        return f"{a}/{b} ({100 * a / b:.1f}\\%)"
    body = ["\\begin{tabular}{@{}l cccc@{}}", "\\toprule",
            " & \\multicolumn{3}{c}{Claude Fable 5.1, asked for the date} & Text-similarity \\\\",
            "\\cmidrule(lr){2-4}",
            " & Blinded & Paraphrased & Blinded & baseline \\\\",
            " & 2000--2023 & 2000--2023 (sample) & 2024--2026 & 2000--2023 \\\\", "\\midrule",
            f"Exact meeting & {cell(blind['exact'], blind['n'])} & {cell(para['exact'], para['n'])} & "
            f"{cell(post['exact'], post['n'])} & $\\le$ {cell(base['br'][0], base['br'][1])}$^a$ \\\\",
            f"Within 1 month & {cell(blind['w1'], blind['n'])} & {cell(para['w1'], para['n'])} & "
            f"{cell(post['w1'], post['n'])} & {cell(base['w1'][0], base['w1'][1])} \\\\",
            f"Within 3 months & {cell(blind['w3'], blind['n'])} & {cell(para['w3'], para['n'])} & "
            f"{cell(post['w3'], post['n'])} & {cell(base['w3'][0], base['w3'][1])} \\\\",
            "\\addlinespace",
            f"ZLB statements, exact & {cell(blind['zlb'], blind['zlbn'])} & "
            f"{cell(para['zlb'], para['zlbn']) if para['zlbn'] else '--'} & -- & "
            f"$\\le$ {cell(base['br'][2], base['br'][3])}$^a$ \\\\",
            f"Confidence ``high'' & {cell(blind['high'], blind['n'])} & {cell(para['high'], para['n'])} & "
            f"{cell(post['high'], post['n'])} & -- \\\\",
            "\\bottomrule", "\\end{tabular}"]
    write("tab_dating.tex", "\n".join(body) + "\n")
    # recognised split
    m = re.search(r"hold meetings probed: (\d+); dated to the exact month: (\d+); not: (\d+)", sec)
    put("probe.hold.n", m.group(1))
    put("probe.hold.recog", m.group(2))
    put("probe.hold.not", m.group(3))
    misses = [r["date"] for r in csv.DictReader(open("probe_fable.csv"))
              if r["err_months"] not in ("", "0")]
    put("probe.blind.misses", ", ".join(misses))
    return blind, para, post, base


def late_probe():
    sec = section(TXT, "L")
    rows = re.findall(r"^  (20\d\dH\d)[ \t]+(\d+)[ \t]+(\d+)[ \t]+(\d+)[ \t]*([^\n]*)$", sec, re.M)
    assert len(rows) == 6, rows
    body = ["\\begin{tabular}{@{}lrrrl@{}}", "\\toprule",
            "Half-year & $n$ & Exact month & Confidence ``high'' & Misses (error in months, confidence) \\\\",
            "\\midrule"]
    for per, n, ex, hi, miss in rows:
        body.append(f"{per} & {n} & {ex} & {hi} & {tex(miss.strip()) or '--'} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_lateprobe.tex", "\n".join(body) + "\n")
    m = re.search(r"pre-2024 statements with\s+all prompts: n (\d+), median ([\d.]+), 90th pct ([\d.]+)", sec)
    put("spread.pre.n", m.group(1))
    put("spread.pre.median", m.group(2))
    put("spread.pre.p90", m.group(3))
    sp = re.findall(r"^  (20\d\d-\d\d-\d\d)\s+(known|not known)\s+" + r"\s+".join([r"(-?[\d.]+)"] * 7), sec, re.M)
    body = ["\\begin{tabular}{@{}ll rrrrr rr@{}}", "\\toprule",
            "Statement & Dating probe & P1 & P2 & P3 & P4 & P5 & SD & Percentile \\\\", "\\midrule"]
    for d, k, *v in sp:
        body.append(f"{d} & {k} & " + " & ".join(f(float(x), 2) for x in v[:5])
                    + f" & {f(float(v[5]), 3)} & {f(float(v[6]), 2)} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_spread.tex", "\n".join(body) + "\n")
    pct = [float(v[6]) for _, _, *v in sp]
    put("spread.pctmin", f(min(pct)))
    put("spread.pctmax", f(max(pct)))
    unv = ("2026-06-17", "2026-07-29")
    rest = [float(v[5]) for d, k, *v in sp if k == "not known" and d not in unv]
    put("spread.unknown.verified", f(statistics.mean(rest), 3))
    put("spread.unknown.verified.n", str(len(rest)))
    m = re.search(r"mean sd, known: ([\d.]+) \(n (\d+)\)", sec)
    put("spread.known", m.group(1))
    put("spread.known.n", m.group(2))
    m = re.search(r"mean sd, not known: ([\d.]+) \(n (\d+)\)", sec)
    put("spread.unknown", m.group(1))
    put("spread.unknown.n", m.group(2))


def spontaneous():
    sec = section(TXT, "I")
    rows = re.findall(r"^  (\S+\.csv)\s+(original|blinded|paraphrased)\s+(\S+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+(\d+)\s+([\d.]+)", sec, re.M)
    label = {"scores_fable.csv": "Claude Fable 5.1, five prompts", "clean_fable.csv": "Claude Fable 5.1, P1 re-run",
             "blind_fable.csv": "Claude Fable 5.1, P1", "para_fable.csv": "Claude Fable 5.1, P1",
             "full_gemini.csv": "Gemini 2.5 Flash, five prompts", "gpt4_p1.csv": "GPT-4, P1"}
    body = ["\\begin{tabular}{@{}lll rrr@{}}", "\\toprule",
            "Scores & Text & Prompt & Replies & Name a date & Own month and year \\\\", "\\midrule"]
    for fn, text, prompt, n, nd, pd, own, po in rows:
        pr = "all" if prompt == "all" else prompt.replace("_", "\\_")
        lab = label[fn] if prompt == "all" else ""
        if fn == "scores_fable.csv" and prompt == "P1_minimal":
            body.append("\\addlinespace[2pt]")
        if fn != "scores_fable.csv" and prompt == "all":
            body.append("\\addlinespace")
        body.append(f"{lab} & {text if prompt == 'all' else ''} & {pr} & {n} & {nd} ({pd}\\%) & {own} ({po}\\%) \\\\")
        key = f"spont.{fn.split('.')[0].replace('_', '')}.{prompt.split('_')[0].lower()}"
        put(key + ".n", n)
        put(key + ".own", own)
        put(key + ".pct", po + "\\%")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_spontaneous.tex", "\n".join(body) + "\n")
    # quotes: blinded examples printed by part I, and hindsight phrases found by
    # searching the stored replies for phrases the review flagged
    import csv as _csv
    quotes = []
    for line in re.findall(r"^    blind (\S+): \.\.\.(.*?)\.\.\.$", sec, re.M)[:2]:
        quotes.append(("blinded", line[0], "P1\\_minimal", line[1]))
    pats = ["which came in January 2001", "setting up the June 2004 hike", "markets had hoped for more",
            "dot plot cut from 4 to 2 hikes", "widely read as teeing up December"]
    seen = set()
    for r in _csv.DictReader(open("scores_fable.csv")):
        for p in pats:
            if p in r["raw_reply"] and p not in seen:
                seen.add(p)
                i = r["raw_reply"].find(p)
                a = max(0, r["raw_reply"].rfind(" ", 0, max(0, i - 70)))
                snippet = r["raw_reply"][a:i + len(p) + 1].strip().replace("\n", " ")
                quotes.append(("original", r["date"], r["prompt"].replace("_", "\\_"), snippet))
    quotes.sort(key=lambda q: (q[0] != "blinded", q[1]))
    body = ["\\begin{tabular}{@{}llp{10.2cm}@{}}", "\\toprule", "Statement & Prompt & Excerpt of the scoring reply \\\\",
            "\\midrule"]
    for kind, d, p, s in quotes:
        body.append(f"{d} ({kind}) & {p} & \\ldots{{}}{tex(s)}\\ldots \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_quotes.tex", "\n".join(body) + "\n")


# --- validity ----------------------------------------------------------------------

def primary():
    sec = section(TXT, "P")
    m = re.search(r"Total regressions printed in\s+this run: (\d+)", sec)
    put("regs.printed", m.group(1))
    put("regs.csv", str(len(ROWS)))
    fam = [r for r in ROWS if r["part"] == "B" and r["model"] == "fable"
           and r["y"] in ("MPS", "MPS_ORTH", "d2", "d10")]
    put("regs.family", str(len(fam)))
    fam.sort(key=lambda r: r["p_nw"])
    m_ = len(fam)
    body = ["\\begin{tabular}{@{}lll rrrr rr@{}}", "\\toprule",
            "Outcome & Meetings & Control & $n$ & $\\hat\\beta$ & NW $t$ & $p$ & Holm $p$ & Bonferroni $p$ \\\\",
            "\\midrule"]
    ylab = {"MPS": "MPS", "MPS_ORTH": "MPS\\_ORTH", "d2": "$d_2$ (bp)", "d10": "$d_{10}$ (bp)"}
    for r in fam:
        prim = (r["y"], r["sample"], r["control"]) == ("MPS", "hold", "-")
        bonf = min(1.0, m_ * r["p_nw"])
        cells = [ylab[r["y"]], r["sample"], "change\\_bp" if r["control"] != "-" else "--", str(r["n"]),
                 f(r["beta"], 3 if r["y"].startswith("MPS") else 2), f(r["t_nw"]), f(r["p_nw"], 3),
                 f(r["p_holm"], 3), f(bonf, 3)]
        if prim:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        body.append(" & ".join(cells) + " \\\\")
        key = f"fam.{r['y']}.{r['sample']}.{'ctrl' if r['control'] != '-' else 'none'}"
        put(key + ".t", f(r["t_nw"]))
        put(key + ".p", f(r["p_nw"], 3))
        put(key + ".holm", f(r["p_holm"], 3))
        put(key + ".bonf", f(bonf, 3))
        put(key + ".beta", f(r["beta"], 3 if r["y"].startswith("MPS") else 2))
        put(key + ".n", str(r["n"]))
    p03 = [r for r in ROWS if r["part"] == "P"][0]
    body += ["\\midrule",
             f"MPS, 2003+ sample & hold & -- & {p03['n']} & {f(p03['beta'], 3)} & {f(p03['t_nw'])} & {f(p03['p_nw'], 3)} & -- & -- \\\\",
             "\\bottomrule", "\\end{tabular}"]
    write("tab_primary.tex", "\n".join(body) + "\n")
    put("prim03.n", str(p03["n"]))
    put("prim03.beta", f(p03["beta"], 3))
    put("prim03.t", f(p03["t_nw"]))
    put("prim03.p", f(p03["p_nw"], 3))
    pr = pick(ROWS, "B", "fable", "MPS", "hold")
    put("prim.n", str(pr["n"]))
    put("prim.beta", f(pr["beta"], 3))
    put("prim.t", f(pr["t_nw"]))
    put("prim.tols", f(pr["t_ols"]))
    put("prim.thc", f(pr["t_hc1"]))
    put("prim.p", f(pr["p_nw"], 3))
    put("prim.r2", f(100 * pr["r2"], 1) + "\\%")
    put("prim.lag", pr["nw_lag"])
    put("prim.first", pr["first"])
    put("prim.last", pr["last"])
    sd = re.search(r"fable: \d+ dScore pairs before 2024-01-01; sd\(dScore\) = ([\d.]+)", TXT).group(1)
    put("fable.sd", sd)
    put("gemini.sd", re.search(r"gemini: \d+ dScore pairs before 2024-01-01; sd\(dScore\) = ([\d.]+)", TXT).group(1))
    put("gpt4.sd", re.search(r"gpt4: \d+ dScore pairs before 2024-01-01; sd\(dScore\) = ([\d.]+)", TXT).group(1))
    for a, b in (("fable", "gemini"), ("fable", "dict"), ("fable", "clean"), ("fable", "blind"),
                 ("fable", "para"), ("fable", "gpt4"), ("gemini", "gpt4"), ("clean", "blind"), ("clean", "para")):
        put(f"corr.{a}.{b}", re.search(rf"corr\({a} dScore, {b} dScore\) = ([\d.]+)", TXT).group(1))
    # effect size in sd units: beta * sd(dScore), in bp of MPS? MPS is in pct points
    put("prim.persd", f(pr["beta"] * float(sd), 3))
    put("prim.persd.ratio", f(pr["beta"] * float(sd) / SD["MPS"], 2))


def secondary():
    models = [("fable", "Fable"), ("gemini", "Gemini"), ("dict", "Dictionary"), ("clean", "Fable P1"),
              ("blind", "P1 blinded"), ("para", "P1 paraphr."), ("gpt4", "GPT-4 P1")]
    ys = [("MPS", "MPS", 3), ("MPS_ORTH", "MPS\\_ORTH", 3), ("t2", "$t_2$ (30-min, bp)", 2),
          ("t10", "$t_{10}$ (30-min, bp)", 2), ("d2", "$d_2$ (daily, bp)", 2), ("d10", "$d_{10}$ (daily, bp)", 2)]
    body = ["\\begin{tabular}{@{}l r " + "c" * len(models) + "@{}}", "\\toprule",
            "Outcome & $n$ & " + " & ".join(m[1] for m in models) + " \\\\", "\\midrule"]
    for y, lab, d in ys:
        rs = [pick(ROWS, "B", m, y, "hold") for m, _ in models]
        n = rs[0]["n"]
        body.append(f"{lab} & {n} & " + " & ".join(f(r["beta"], d) for r in rs) + " \\\\")
        body.append(" & & " + " & ".join(f"({f(r['t_nw'])})" for r in rs) + " \\\\")
        body.append("\\addlinespace[3pt]")
        for (m, _), r in zip(models, rs):
            put(f"hold.{m}.{y}.t", f(r["t_nw"]))
            put(f"hold.{m}.{y}.beta", f(r["beta"], d))
            put(f"hold.{m}.{y}.p", f(r["p_nw"], 3))
            put(f"hold.{m}.{y}.n", str(r["n"]))
    body[-1:] = ["\\bottomrule", "\\end{tabular}"]
    write("tab_secondary.tex", "\n".join(body) + "\n")
    # all-meeting rows quoted in text
    for m in ("fable", "gemini"):
        for y in ("MPS", "t2", "t10", "d2", "d10"):
            r = pick(ROWS, "B", m, y, "all")
            put(f"all.{m}.{y}.t", f(r["t_nw"]))
        r = pick(ROWS, "B", m, "MPS", "all", "change_bp")
        put(f"allctrl.{m}.MPS.t", f(r["t_nw"]))
    for y in ("t2", "t10"):
        r = pick(ROWS, "B", "fable", y, "all", "change_bp")
        put(f"allctrl.fable.{y}.t", f(r["t_nw"]))


def robustness():
    variants = [("default", ROWS, "Default: policy corpus, prompt-demeaned consensus"),
                ("strict", VAR["strict"][1], "Strict corpus (also drops 2007-08-17, 2020-03-23)"),
                ("all", VAR["all"][1], "All files (the seven notices kept)"),
                ("matched", VAR["matched"][1], "Consensus over prompts common to both statements"),
                ("raw", VAR["raw"][1], "Raw consensus (no prompt fixed effects)"),
                ("p1", VAR["p1"][1], "One prompt only (P1\\_minimal)")]
    ys = ("MPS", "t2", "t10", "d2", "d10")
    body = ["\\begin{tabular}{@{}l " + "r" * (2 * len(ys)) + "@{}}", "\\toprule",
            " & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{y if y == 'MPS' else '$' + y[0] + '_{' + y[1:] + '}$'}}}" for y in ys) + " \\\\",
            "".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(ys))),
            "Variant & " + " & ".join("$n$ & $t$" for _ in ys) + " \\\\", "\\midrule"]
    for key, rows, lab in variants:
        cells = []
        for y in ys:
            r = pick(rows, "B", "fable", y, "hold")
            cells += [str(r["n"]), f(r["t_nw"])]
            put(f"var.{key}.{y}.t", f(r["t_nw"]))
            put(f"var.{key}.{y}.n", str(r["n"]))
        body.append(lab + " & " + " & ".join(cells) + " \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_variants.tex", "\n".join(body) + "\n")
    for key in ("strict", "all"):
        m = re.search(r"--corpus \w+: (\d+) statements", VAR[key][0])
        put(f"var.{key}.nstmt", m.group(1))
    # Holm p of the primary under the strict corpus, and its d10 row
    for key in ("strict",):
        for y in ("MPS", "d2", "d10"):
            r = pick(VAR[key][1], "B", "fable", y, "hold")
            put(f"var.{key}.{y}.holm", f(r["p_holm"], 3))
    # placebo days and influence (part K)
    sec = section(TXT, "K")
    plre = r"^  (d2|d10)\s+([\d.]+)\s+(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+([\d.]+)$"
    body = ["\\begin{tabular}{@{}ll rrrrrr@{}}", "\\toprule",
            "Corpus & Outcome & Actual $t$ & Placebo days & $|t|>1.96$ & $|t|\\ge$ actual & 95th pct.\\ $|t|$ & Max $|t|$ \\\\",
            "\\midrule"]
    for ck, lab, txt in (("default", "Policy (default)", TXT), ("strict", "Strict", VAR["strict"][0]),
                         ("all", "All files", VAR["all"][0])):
        pl = re.findall(plre, section(txt, "K"), re.M)
        for i, (y, real, n, a, b, p95, mx) in enumerate(pl):
            body.append(f"{lab if i == 0 else ''} & $d_{{{y[1:]}}}$ & {real} & {n} & {a} & {b} & {p95} & {mx} \\\\")
            pre = "placebo" if ck == "default" else f"placebo.{ck}"
            for k, v in (("real", real), ("n", n), ("over196", a), ("overreal", b), ("p95", p95), ("max", mx)):
                put(f"{pre}.{y}.{k}", v)
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_placebo.tex", "\n".join(body) + "\n")
    inf = re.findall(r"^  (MPS|d2|d10|t2|t10)\s+([\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(.*?)\n\s+dropped: (.*)$", sec, re.M)
    body = ["\\begin{tabular}{@{}l rrr l@{}}", "\\toprule",
            "Outcome & Full $t$ & LOO min & LOO max & $t$ after dropping 1, 2, \\ldots, 5 meetings (greedy) \\\\",
            "\\midrule"]
    for y, full, lo, hi, path, dropped in inf:
        ylab = "MPS" if y == "MPS" else f"${y[0]}_{{{y[1:]}}}$"
        steps = [f(float(x)) for x in path.split(" -> ")]
        body.append(f"{ylab} & {full} & {f(float(lo))} & {f(float(hi))} & {' $\\to$ '.join(steps)} \\\\")
        body.append(f" & \\multicolumn{{4}}{{l}}{{\\footnotesize dropped in order: {dropped.strip()}}} \\\\")
        put(f"infl.{y}.loomin", f(float(lo)))
        put(f"infl.{y}.loomax", f(float(hi)))
        put(f"infl.{y}.after5", steps[-1])
        put(f"infl.{y}.after1", steps[0])
        put(f"infl.{y}.dropped", dropped.strip())
        if y == "MPS":
            put("infl.MPS.path", " $\\to$ ".join([full] + steps))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_influence.tex", "\n".join(body) + "\n")
    for ck in ("strict", "all"):
        m = re.search(r"^  MPS\s+([\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(.*?)$", section(VAR[ck][0], "K"), re.M)
        put(f"infl.{ck}.MPS.after5", f(float(m.group(4).split(" -> ")[-1])))
    # GPT-4 coarseness
    m = re.search(r"GPT-4 P1: (\d+) scores, (\d+) distinct values, (\d+) at -1 \((\d+)%\)", sec)
    put("gpt4.nscores", m.group(1))
    put("gpt4.distinct", m.group(2))
    put("gpt4.atminus1", m.group(3))
    put("gpt4.atminus1pct", m.group(4) + "\\%")
    m = re.search(r"hold dScores exactly 0: GPT-4 (\d+)/(\d+) \((\d+)%\), Fable (\d+)/(\d+); ZLB statements at -1: (\d+)/(\d+)", sec)
    put("gpt4.zero", m.group(1))
    put("gpt4.zeron", m.group(2))
    put("gpt4.zeropct", m.group(3) + "\\%")
    put("fable.zero", m.group(4))
    put("fable.zeron", m.group(5))
    put("gpt4.zlbfloor", m.group(6))
    put("gpt4.zlbn", m.group(7))
    # exploratory checks
    ex = list(csv.DictReader(open(os.path.join(RUNS, "extra.csv"))))
    body = ["\\begin{tabular}{@{}l rrrr l@{}}", "\\toprule",
            "Check (outcome MPS, hold meetings) & $n$ & $\\hat\\beta$ & NW $t$ & $p$ & Sample \\\\", "\\midrule"]
    keys = ["sub0007", "sub0815", "sub1623", "level", "lagmps", "lagds", "decpara", "decparares",
            "decblind", "decblindres", "predpart", "predsame", "winsor"]
    labels = {"sub0007": "Subperiod 2000--2007", "sub0815": "Subperiod 2008--2015",
              "sub1623": "Subperiod 2016--2023", "level": "Score level instead of its change",
              "lagmps": "Primary + previous statement's MPS (dScore coef.)",
              "lagds": "Primary + lagged dScore (dScore coef.)",
              "decpara": "Joint: paraphrased dScore", "decparares": "\\quad and clean $-$ paraphrased",
              "decblind": "Joint: blinded dScore", "decblindres": "\\quad and clean $-$ blinded",
              "predpart": "Outcome MPS $-$ MPS\\_ORTH (predictable part)",
              "predsame": "MPS on the same meetings", "winsor": "Primary, $x$ and $y$ winsorised at 2.5/97.5\\%"}
    for k, r in zip(keys, ex):
        if k in ("level", "lagmps", "decpara", "decblind", "predpart", "winsor"):
            body.append("\\addlinespace[3pt]")
        body.append(f"{labels[k]} & {r['n']} & {f(float(r['beta']), 3)} & {f(float(r['t_nw']))} & "
                    f"{fp(float(r['p_nw']))} & {r['first'][:7]}--{r['last'][:7]} \\\\")
        put(f"extra.{k}.t", f(float(r["t_nw"])))
        put(f"extra.{k}.n", r["n"])
        put(f"extra.{k}.p", fp(float(r["p_nw"])))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_extra.tex", "\n".join(body) + "\n")
    put("regs.extra", str(len(ex)))
    xt0 = open(os.path.join(RUNS, "extra.txt")).read()
    m = re.search(r"Spearman rho ([\d.]+); permutation p \(2000 shuffles of dScore, seed 1\) ([\d.]+)", xt0)
    put("prim.spearman", f(float(m.group(1))))
    put("prim.perm", f(float(m.group(2)), 3))
    m = re.search(r"greedy drop \(fast NW, check vs part K\): full t ([\d.]+) -> (.*?); dropped (.*)$", xt0, re.M)
    assert m.group(3).strip() == V["infl.MPS.dropped"], "fast greedy differs from part K"
    m = re.search(r"median full t ([\d.]+), median t after greedy drop of 5 ([\d.]+), share at or below the actual ([\d.]+): ([\d.]+)", xt0)
    put("bench.full", m.group(1))
    put("bench.after", m.group(2))
    put("bench.share", f(float(m.group(4)), 2))
    put("bench.sharepct", f(100 * float(m.group(4)), 0) + "\\%")
    jz, jtf, jtg = [], [], []
    for y, n, tf, tg, z, lo, hi in re.findall(r"J-drop5 (\S+)\s+n (\d+)\s+joint t Fable (-?[\d.]+) Gemini (-?[\d.]+)\s+gap z (-?[\d.]+)\s+\[(-?[\d.]+), (-?[\d.]+)\]", xt0):
        jz.append(float(z)); jtf.append(float(tf)); jtg.append(float(tg))
        assert float(lo) > 0, "J-drop5 interval includes 0: update text"
    put("jdrop.zmin", f(min(jz))); put("jdrop.zmax", f(max(jz)))
    put("jdrop.tFmin", f(min(jtf))); put("jdrop.tFmax", f(max(jtf)))
    put("jdrop.tGmin", f(min(jtg))); put("jdrop.tGmax", f(max(jtg)))
    m = re.search(r"influential 5 (\d+)/(\d+), other hold (\d+)/(\d+)", xt0)
    a1, n1, a2, n2 = map(int, m.groups())
    put("name.infl", f"{a1} of {n1}"); put("name.inflpct", f(100 * a1 / n1, 0) + "\\%")
    put("name.other", f"{a2} of {n2}"); put("name.otherpct", f(100 * a2 / n2, 0) + "\\%")
    keymap = {"changes.csv": "gem", "changes_claude.csv": "haiku", "changes_openai.csv": "mini",
              "changes_frontier.csv": "fable"}
    drops = []
    for fn, n, hk, ct, raw, rl, rd, dl, dd in re.findall(
            r"^  (changes\S*\.csv)\s+n (\d+) \(hikes (\d+), cuts (\d+)\)\s+raw ([\d.]+)\s+resid linear ([\d.]+)"
            r"\s+resid dummies ([\d.]+)\s+drop (\d+)% / (\d+)%", xt0, re.M):
        put(f"dummy.{keymap[fn]}.drop", dd + "\\%")
        put(f"dummy.{keymap[fn]}.resid", rd)
        if keymap[fn] != "fable":
            drops.append(int(dd))
        put("block.hikes", hk)
        put("block.cuts", ct)
    put("dummy.cheap.min", f"{min(drops)}\\%")
    put("dummy.cheap.max", f"{max(drops)}\\%")
    xt = open(os.path.join(RUNS, "extra.txt")).read()
    for d in ("2009-03-18", "2013-09-18"):
        m = re.search(rf"{d}: Fable dScore ([+-][\d.]+), d10 ([+-]\d+) bp", xt)
        put(f"lsap.{d}.ds", f(float(m.group(1)) + 0.0, 2))
        put(f"lsap.{d}.d10", m.group(2).replace("-", "$-$"))


def fable_vs_gemini():
    sec = section(TXT, "J")
    rows = re.findall(r"^  (MPS|d2|d10|t2|t10)\s+(\d+)" + r"\s+(-?[\d.]+)" * 9 + r"\s+\[(-?[\d.]+), (-?[\d.]+)\]", sec, re.M)
    body = ["\\begin{tabular}{@{}l r rr rr rrr@{}}", "\\toprule",
            " & & \\multicolumn{2}{c}{Joint: Fable} & \\multicolumn{2}{c}{Joint: Gemini} & \\multicolumn{3}{c}{Gap in per-SD slopes} \\\\",
            "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(l){7-9}",
            "Outcome & $n$ & $\\hat\\beta$ & NW $t$ & $\\hat\\beta$ & NW $t$ & Gap & $z$ & 95\\% interval \\\\", "\\midrule"]
    for y, n, bF, tF, bG, tG, sF, sG, gap, se, z, lo, hi in rows:
        d = 3 if y == "MPS" else 2
        ylab = "MPS" if y == "MPS" else f"${y[0]}_{{{y[1:]}}}$"
        body.append(f"{ylab} & {n} & {f(float(bF), d)} & {f(float(tF))} & {f(float(bG), d)} & {f(float(tG))} & "
                    f"{f(float(gap), d)} & {f(float(z))} & [{f(float(lo), d)}, {f(float(hi), d)}] \\\\")
        put(f"j.{y}.tF", f(float(tF)))
        put(f"j.{y}.tG", f(float(tG)))
        put(f"j.{y}.z", f(float(z)))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_gemini.tex", "\n".join(body) + "\n")
    zs = [float(r[10]) for r in rows]
    tFs = [float(r[3]) for r in rows]
    tGs = [float(r[5]) for r in rows]
    put("j.zmin", f(min(zs)))
    put("j.zmax", f(max(zs)))
    put("j.tFmin", f(min(tFs)))
    put("j.tFmax", f(max(tFs)))
    put("j.tGmin", f(min(tGs)))   # most negative
    put("j.tGmax", f(max(tGs)))
    # human labels, part N
    sec = section(TXT, "N")
    m = re.search(r"(\d+) statements with 2\+ labelled sentences \((\d{4})-(\d{4})\)", TXT)
    put("tdw.n", m.group(1))
    put("tdw.first", m.group(2))
    put("tdw.last", m.group(3))
    rows = re.findall(r"^  (fable|gemini|dict|gpt4)\s+(\d+)\s+([\d.]+)\s+(\d+)\s+([\d.]+)\s+(\d+)\s+([\d.]+)", sec, re.M)
    name = {"fable": "Claude Fable 5.1 (five prompts)", "gemini": "Gemini 2.5 Flash (five prompts)",
            "dict": "Dictionary word count", "gpt4": "GPT-4 (P1)"}
    body = ["\\begin{tabular}{@{}l rr rr@{}}", "\\toprule",
            " & \\multicolumn{2}{c}{All statements} & \\multicolumn{2}{c}{Hold meetings} \\\\",
            "\\cmidrule(lr){2-3}\\cmidrule(l){4-5}",
            "Score & $n$ & $r$ & $n$ & $r$ \\\\", "\\midrule"]
    for m_, n, r, nh, rh, nc, rc in rows:
        body.append(f"{name[m_]} & {n} & {r} & {nh} & {rh} \\\\")
        put(f"tdw.{m_}.r", r)
        put(f"tdw.{m_}.rhold", rh)
        put(f"tdw.{m_}.rchg", rc)
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_tdw.tex", "\n".join(body) + "\n")
    n_lab = sum(1 for _ in csv.DictReader(open("tdw_labels.csv")))
    put("tdw.matches", str(n_lab))
    put("tdw.stmts", str(len({r["date"] for r in csv.DictReader(open("tdw_labels.csv"))})))


def cutoff_tests():
    sec = section(TXT, "C")
    put("post.pairs", re.search(r"(\d+) dScore pairs, 2024", sec).group(1))
    body = ["\\begin{tabular}{@{}ll rrrr@{}}", "\\toprule",
            "Outcome & Meetings & $n$ & Fable $t$ & Gemini $t$ & GPT-4 $t$ \\\\", "\\midrule"]
    for y in ("d2", "d10"):
        for s in ("all", "hold"):
            rs = {m: pick(ROWS, "C", m, y, s) for m in ("fable", "gemini", "gpt4")}
            body.append(f"${y[0]}_{{{y[1:]}}}$ & {s} & {rs['fable']['n']} & {f(rs['fable']['t_nw'])} & "
                        f"{f(rs['gemini']['t_nw'])} & {f(rs['gpt4']['t_nw'])} \\\\")
            for m in rs:
                put(f"post.{m}.{y}.{s}.t", f(rs[m]["t_nw"]))
            put(f"post.{y}.{s}.n", str(rs["fable"]["n"]))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_post.tex", "\n".join(body) + "\n")
    sec = section(TXT, "D")
    rows = re.findall(r"^  (d2|d10)\s+(all|hold)\s+([\d.]+)\s+(\d+)\s+(\d+)\s+(\d+)%\s+([\d.]+)\s+(\d+)", sec, re.M)
    body = ["\\begin{tabular}{@{}ll rrrrrr@{}}", "\\toprule",
            "Outcome & Meetings & Pre-2024 $R^2$ & $n$ for 80\\% power & $n$ now & Power now & Pairs per year & Years more \\\\",
            "\\midrule"]
    pw = []
    for y, s, r2, need, now, power, per, yrs in rows:
        body.append(f"${y[0]}_{{{y[1:]}}}$ & {s} & {r2} & {need} & {now} & {power}\\% & {per} & {yrs} \\\\")
        pw.append(int(power))
        put(f"power.{y}.{s}.need", need)
        put(f"power.{y}.{s}.years", yrs)
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_power.tex", "\n".join(body) + "\n")
    put("power.min", f"{min(pw)}\\%")
    put("power.max", f"{max(pw)}\\%")
    # GPT-4 before / after cutoff (part H)
    hrows = [r for r in ROWS if r["part"] == "H" and r["control"] == "-"]
    body = ["\\begin{tabular}{@{}ll rrr rr@{}}", "\\toprule",
            " & & \\multicolumn{3}{c}{GPT-4 (P1)} & \\multicolumn{2}{c}{Fable (consensus)} \\\\",
            "\\cmidrule(lr){3-5}\\cmidrule(l){6-7}",
            "Outcome & Window & $n$ & $\\hat\\beta$ & $t$ & $\\hat\\beta$ & $t$ \\\\", "\\midrule"]
    for y in ("MPS", "d2", "d10"):
        for s in ("all-pre", "hold-pre", "all-post", "hold-post"):
            g = [r for r in hrows if r["model"] == "gpt4" and r["y"] == y and r["sample"] == s]
            fa = [r for r in hrows if r["model"] == "fable" and r["y"] == y and r["sample"] == s]
            if not g:
                continue
            g = g[0]
            d = 3 if y == "MPS" else 2
            fcell = f"{f(fa[0]['beta'], d)} & {f(fa[0]['t_nw'])}" if fa else "& "
            ylab = "MPS" if y == "MPS" else f"${y[0]}_{{{y[1:]}}}$"
            body.append(f"{ylab} & {s.replace('-', ', ')} & {g['n']} & {f(g['beta'], d)} & {f(g['t_nw'])} & {fcell} \\\\")
            put(f"h.gpt4.{y}.{s}.t", f(g["t_nw"]))
            if fa:
                put(f"h.fable.{y}.{s}.t", f(fa[0]["t_nw"]))
                put(f"h.fable.{y}.{s}.n", str(fa[0]["n"]))
            put(f"h.gpt4.{y}.{s}.n", str(g["n"]))
        body.append("\\addlinespace[2pt]")
    body[-1:] = ["\\bottomrule", "\\end{tabular}"]
    write("tab_gpt4.tex", "\n".join(body) + "\n")


def beyond_and_gaps():
    frows = [r for r in ROWS if r["part"] == "F"]
    sec = section(TXT, "F")
    gains = re.findall(r"^  (d2|d10)\s+(all|hold)\s+(\S+)\s+(\w+)\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+([\d.]+)", sec, re.M)
    body = ["\\begin{tabular}{@{}lll r rrr rr@{}}", "\\toprule",
            "Outcome & Meetings & Score & $n$ & $R^2$ base & $R^2$ + dScore & Gain (pp) & $\\hat\\beta$ & NW $t$ \\\\", "\\midrule"]
    fg = []
    for y, s, ctrl, m, n, b0, b1, gain, beta, t, p in gains:
        if m not in ("fable", "gemini", "clean", "blind", "para"):
            continue
        body.append(f"${y[0]}_{{{y[1:]}}}$ & {s} & {m} & {n} & {b0} & {b1} & {gain} & {f(float(beta))} & {f(float(t))} \\\\")
        if m == "fable":
            fg.append((float(gain), float(t)))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_beyond.tex", "\n".join(body) + "\n")
    put("beyond.fable.gainmax", f(max(g for g, _ in fg)))
    put("beyond.fable.gainmin", f(min(g for g, _ in fg)))
    put("beyond.fable.tmax", f(max(abs(t) for _, t in fg)))
    allg = [float(g[7]) for g in gains]
    put("beyond.gainmax", f(max(allg)))
    sec = section(TXT, "G")
    rows = re.findall(r"^  (MPS|d2|d10)\s+(blind|para|gpt4)\s+(\d+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+([\d.]+)\s+(-?[\d.]+)\s+\[(-?[\d.]+), (-?[\d.]+)\]", sec, re.M)
    body = ["\\begin{tabular}{@{}ll r rrr rr@{}}", "\\toprule",
            "Outcome & Other score & $n$ & $\\hat\\beta$ clean & $\\hat\\beta$ other & Gap & $z$ & 95\\% interval \\\\", "\\midrule"]
    for y, o, n, bc, bo, gap, se, z, lo, hi in rows:
        if o == "gpt4":
            continue
        d = 3 if y == "MPS" else 2
        ylab = "MPS" if y == "MPS" else f"${y[0]}_{{{y[1:]}}}$"
        body.append(f"{ylab} & {'blinded' if o == 'blind' else 'paraphrased'} & {n} & {f(float(bc), d)} & {f(float(bo), d)} & "
                    f"{f(float(gap), d)} & {f(float(z))} & [{f(float(lo), d)}, {f(float(hi), d)}] \\\\")
        put(f"g.{y}.{o}.z", f(float(z)))
        GZ.append((float(z), float(lo) > 0 or float(hi) < 0))
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_gaps.tex", "\n".join(body) + "\n")
    put("g.n", str(len(GZ)))
    put("g.zmin", f(min(z for z, _ in GZ)))
    put("g.zmax", f(max(z for z, _ in GZ)))
    put("g.over196", str(sum(abs(z) > 1.96 for z, _ in GZ)))
    # the text says every interval includes zero; fail loudly if that stops being true
    assert sum(e for _, e in GZ) == 0, "a part G interval excludes zero: update section 6.7"


def truncated():
    """Replies stored cut at 300 characters, and whether the +-1 scores among
    them agree in sign with the statement's other prompts."""
    import analysis as A
    for lab, path in (("fable", A.FABLE), ("gemini", A.GEMINI)):
        rows = [r for r in csv.DictReader(open(path)) if r.get("raw_reply")]
        cut = [r for r in rows if len(r["raw_reply"]) == 300]
        put(f"trunc.{lab}", str(len(cut)))
        put(f"trunc.{lab}.of", str(len(rows)))
        sc = A.collapse(A.load_cells(path)[0])
        ext, agree = 0, 0
        for r in cut:
            try:
                v = float(r["score"])
            except ValueError:
                continue
            if abs(v) != 1.0 or r["date"] not in sc or (r["date"], r["prompt"], r.get("source")) in A.PARSE_ERRORS:
                continue
            others = [x for p, x in sc[r["date"]].items() if p != r["prompt"]]
            if not others:
                continue
            ext += 1
            agree += (statistics.mean(others) > 0) == (v > 0)
        put(f"trunc.{lab}.ext", str(ext))
        put(f"trunc.{lab}.agree", str(agree))


def parse_audit():
    sec = TXT[TXT.index("PARSE AUDIT"):]
    rows = re.findall(r"^  (\S+?\.csv)\s*(\d{4}-\d\d-\d\d)\s+(\S+)\s+stored ([+-][\d.]+)\s+reply '(.*?)'", sec, re.M)
    body = ["\\begin{tabular}{@{}lllrl@{}}", "\\toprule", "File & Statement & Prompt & Stored & Reply (start) \\\\",
            "\\midrule"]
    for fn, d, p, s, r in rows:
        r = r if len(r) <= 34 else r[:34] + "..."
        body.append(f"\\texttt{{{tex(fn)}}} & {d} & {tex(p)} & {f(float(s))} & \\texttt{{{tex(r)}}} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_parse.tex", "\n".join(body) + "\n")
    put("parse.dropped", str(len(rows)))


def prompts():
    from pilot import PROMPTS
    import probe
    import paraphrase
    out = []
    for p in PROMPTS:
        out.append(f"\\paragraph{{{p['name'].replace('_', '\\_')}}}" + (" (answer sign flipped back in code)" if p["flip"] else ""))
        out.append("\\begin{Verbatim}[breaklines,fontsize=\\small]\n" + p["text"] + "\n\\end{Verbatim}")
    write("prompts_scoring.tex", "\n".join(out) + "\n")
    write("prompt_probe.tex", "\\begin{Verbatim}[breaklines,fontsize=\\small]\n" + probe.PROMPT + "\n\\end{Verbatim}\n")
    write("prompt_para.tex", "\\begin{Verbatim}[breaklines,fontsize=\\small]\n" + paraphrase.PROMPT + "\n\\end{Verbatim}\n")


def runs_table():
    """One row per score file: model, prompts, statements, period, text version."""
    files = [("changes.csv", "Reliability block", "original"),
             ("changes_claude.csv", "Reliability block", "original"),
             ("changes_openai.csv", "Reliability block", "original"),
             ("changes_frontier.csv", "Reliability block", "original"),
             ("changes_2004.csv", "Reliability, 2004--07", "original"),
             ("full_gemini.csv", "Full corpus", "original"),
             ("scores_fable.csv", "Full corpus", "original"),
             ("gpt4_p1.csv", "Full corpus (cutoff model)", "original, cleaned"),
             ("clean_fable.csv", "Re-score, pre-2024", "original, cleaned"),
             ("blind_fable.csv", "Re-score, pre-2024", "blinded"),
             ("para_fable.csv", "Re-score, pre-2024", "paraphrased"),
             ("scores_dict.csv", "Full corpus (no LLM)", "original, cleaned")]
    body = ["\\begin{tabular}{@{}llrrl@{}}", "\\toprule",
            "Model (OpenRouter ID) & Use & Prompts & Statements & Text \\\\", "\\midrule"]
    for fn, use, text in files:
        rows = [r for r in csv.DictReader(open(fn)) if r.get("score") not in (None, "")]
        model = {r["model"] for r in rows}
        assert len(model) == 1, fn
        prompts = {r["prompt"] for r in rows}
        dates = sorted({r["date"] for r in rows})
        mid = model.pop()
        mid = "word count (no model)" if mid.startswith("dictionary") else f"\\texttt{{{tex(mid)}}}"
        body.append(f"{mid} & {use} & {len(prompts)} & "
                    f"{len(dates)} & {text} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_runs.tex", "\n".join(body) + "\n")


def yields_check():
    """yields.csv against the FRED DGS2/DGS10 downloads, to the hundredth."""
    y = {r["date"]: r for r in csv.DictReader(open("yields.csv"))}
    match = total = 0
    first = last = None
    for col, fn in (("y2", "fred_DGS2.csv"), ("y10", "fred_DGS10.csv")):
        for r in csv.DictReader(open(fn)):
            d = r.get("observation_date") or r.get("DATE")
            v = r.get("DGS2") if col == "y2" else r.get("DGS10")
            if d in y and v not in ("", ".", None) and y[d].get(col):
                total += 1
                match += abs(float(v) - float(y[d][col])) < 0.005
                first = min(first or d, d)
                last = max(last or d, d)
    days = total // 2
    assert match == total, (match, total)
    put("fred.days", str(days))
    put("fred.first", first)
    put("fred.last", last)


def human_sheet():
    rows = list(csv.DictReader(open("human_labels.csv")))
    put("humansheet.n", str(len(rows)))
    put("humansheet.labelled", str(sum(bool((r.get("label") or "").strip()) for r in rows)))


def nav_year():
    """Statements whose ORIGINAL scored text (first commit, before the
    2026-09-25 clean-up) ended with a page-navigation line naming a year."""
    import subprocess
    first = "1e6e13f"
    files = subprocess.run(["git", "ls-tree", "--name-only", first, "statements/"],
                           capture_output=True, text=True, check=True).stdout.split()
    nav, own, dates = 0, 0, []
    for fn in files:
        t = subprocess.run(["git", "show", f"{first}:{fn}"], capture_output=True, text=True).stdout
        m = re.search(r"(\d{4}) Monetary policy Home", t[-80:])
        if m:
            nav += 1
            own += m.group(1) == os.path.basename(fn)[:4]
            dates.append(os.path.basename(fn)[:10])
    put("nav.n", str(nav))
    put("nav.own", str(own))
    put("nav.first", min(dates)[:4])
    put("nav.last", max(dates)[:4])


def paraphrase_stats():
    rows = list(csv.DictReader(open("para_log.csv")))
    ok = [r for r in rows if r.get("overlap4")]
    ov = [float(r["overlap4"]) for r in ok]
    ratio = [int(r["words_out"]) / int(r["words_in"]) for r in ok if r.get("words_out")]
    put("para.n", str(len(ok)))
    put("para.overlap.mean", f(statistics.mean(ov), 3))
    put("para.overlap.max", f(max(ov), 3))
    put("para.length", f(statistics.mean(ratio), 2))
    put("para.retries", str(sum(r["tries"] == "2" for r in rows)))
    flagged = [r["date"] for r in rows if r["flags"]]
    put("para.flagged", str(len(flagged)))
    put("para.flagged.dates", " and ".join(flagged))
    put("para.passed", str(len(rows) - len(flagged)))
    six = 0
    for fn in os.listdir("statements_para"):
        t = open(os.path.join("statements_para", fn)).read()
        if "6-1/2 percent" in t or "6.5 percent" in t:
            six += 1
    put("para.sixhalf", str(six))


# --- figures (pgfplots) -------------------------------------------------------------

def fig_dating(blind, para, post, base):
    pct = lambda a, b: 100 * a / b
    os.makedirs(FIG, exist_ok=True)
    series = [("Fable, blinded (n=%d)" % blind["n"], [pct(blind["exact"], blind["n"]), pct(blind["w1"], blind["n"]), pct(blind["w3"], blind["n"])]),
              ("Fable, paraphrased (n=%d)" % para["n"], [pct(para["exact"], para["n"]), pct(para["w1"], para["n"]), pct(para["w3"], para["n"])]),
              ("Text similarity, no memory (n=%d)" % base["w1"][1], [pct(base["br"][0], base["br"][1]), pct(base["w1"][0], base["w1"][1]), pct(base["w3"][0], base["w3"][1])])]
    cats = ["Exact meeting", "Within 1 month", "Within 3 months"]
    plots = []
    styles = ["fill=black!80", "fill=black!45", "pattern=north east lines"]
    for (name, vals), st in zip(series, styles):
        coords = " ".join(f"({c},{v:.1f})" for c, v in zip(cats, vals))
        plots.append(f"\\addplot[{st}, draw=black] coordinates {{{coords}}};\n\\addlegendentry{{{tex(name)}}}")
    body = ("\\begin{tikzpicture}\n\\begin{axis}[ybar, bar width=16pt, width=0.95\\linewidth, height=6.2cm,\n"
            "  ymin=0, ymax=112, ytick={0,25,50,75,100}, ylabel={Share of statements (\\%)}, symbolic x coords={" + ",".join(cats) + "},\n"
            "  xtick=data, enlarge x limits=0.2, legend style={at={(0.5,-0.14)}, anchor=north, legend columns=-1, font=\\footnotesize, draw=none, /tikz/every even column/.append style={column sep=8pt}},\n"
            "  legend cell align=left, nodes near coords, nodes near coords style={font=\\scriptsize, /pgf/number format/fixed, /pgf/number format/precision=0}, ymajorgrids, major grid style={black!15}]\n"
            + "\n".join(plots) + "\n\\end{axis}\n\\end{tikzpicture}\n")
    open(os.path.join(FIG, "fig_dating.tex"), "w").write("% generated by paper/make_tables.py\n" + body)


def fig_icc(icc):
    os.makedirs(FIG, exist_ok=True)
    rows = icc[:4]
    names = [MODELNAME.get(r[0], r[0]) for r in rows]
    raw = " ".join(f"({n},{r[4]})" for n, r in zip(names, rows))
    res = " ".join(f"({n},{r[5]})" for n, r in zip(names, rows))
    chg = " ".join(f"({n},{r[7]})" for n, r in zip(names, rows))
    body = ("\\begin{tikzpicture}\n\\begin{axis}[ybar, bar width=13pt, width=0.95\\linewidth, height=6.2cm,\n"
            "  ymin=0, ymax=1.12, ytick={0,0.25,0.5,0.75,1}, ylabel={ICC(3,1) across five prompts}, symbolic x coords={" + ",".join(names) + "},\n"
            "  xtick=data, enlarge x limits=0.15, legend style={at={(0.5,-0.14)}, anchor=north, legend columns=-1, font=\\footnotesize, draw=none, /tikz/every even column/.append style={column sep=8pt}},\n"
            "  legend cell align=left, nodes near coords, nodes near coords style={font=\\scriptsize, /pgf/number format/fixed, /pgf/number format/precision=2}, ymajorgrids, major grid style={black!15}]\n"
            f"\\addplot[fill=black!80, draw=black] coordinates {{{raw}}};\n\\addlegendentry{{Levels (raw)}}\n"
            f"\\addplot[fill=black!35, draw=black] coordinates {{{res}}};\n\\addlegendentry{{Levels after removing the rate decision}}\n"
            f"\\addplot[pattern=north east lines, draw=black] coordinates {{{chg}}};\n\\addlegendentry{{Meeting-to-meeting changes}}\n"
            "\\end{axis}\n\\end{tikzpicture}\n")
    open(os.path.join(FIG, "fig_icc.tex"), "w").write("% generated by paper/make_tables.py\n" + body)


def fig_scatter():
    pts = list(csv.DictReader(open(os.path.join(RUNS, "scatter.csv"))))
    infl = V["infl.MPS.dropped"].split(", ")
    norm = " ".join(f"({p['dscore']},{p['mps']})" for p in pts if p["date"] not in infl)
    hi = [p for p in pts if p["date"] in infl]
    hic = " ".join(f"({p['dscore']},{p['mps']})" for p in hi)
    labels = "\n".join(f"\\node[font=\\scriptsize, anchor={'north west' if float(p['mps']) < 0 else 'south east'}, inner sep=2pt] at (axis cs:{p['dscore']},{p['mps']}) {{{p['date']}}};" for p in hi)
    pr = pick(ROWS, "B", "fable", "MPS", "hold")
    xs = [float(p["dscore"]) for p in pts]
    ys = [float(p["mps"]) for p in pts]
    mx, my = statistics.mean(xs), statistics.mean(ys)
    a = my - pr["beta"] * mx
    lo, hi_ = min(xs), max(xs)
    body = ("\\begin{tikzpicture}\n\\begin{axis}[width=0.92\\linewidth, height=7cm, xlabel={Change in Fable stance score (dScore)},\n"
            "  ylabel={MPS (percentage points)}, ymajorgrids, xmajorgrids, major grid style={black!12}, clip=false]\n"
            f"\\addplot[only marks, mark=o, mark size=1.6pt, black!60] coordinates {{{norm}}};\n"
            f"\\addplot[only marks, mark=*, mark size=2.2pt, black] coordinates {{{hic}}};\n"
            f"\\addplot[domain={lo:.3f}:{hi_:.3f}, samples=2, thick, black] {{{a:.5f} + {pr['beta']:.5f}*x}};\n"
            + labels + "\n\\end{axis}\n\\end{tikzpicture}\n")
    open(os.path.join(FIG, "fig_scatter.tex"), "w").write("% generated by paper/make_tables.py\n" + body)


def main():
    corpus()
    descriptives()
    icc = reliability()
    blind, para, post, base = recognition()
    late_probe()
    spontaneous()
    primary()
    secondary()
    robustness()
    fable_vs_gemini()
    cutoff_tests()
    beyond_and_gaps()
    parse_audit()
    truncated()
    prompts()
    paraphrase_stats()
    nav_year()
    human_sheet()
    runs_table()
    yields_check()
    fig_dating(blind, para, post, base)
    fig_icc(icc)
    fig_scatter()
    lines = ["% generated by paper/make_tables.py - every number quoted in the text",
             "\\makeatletter",
             "\\newcommand{\\R}[1]{\\@ifundefined{R@#1}{\\textbf{??#1??}\\PackageWarning{numbers}{undefined key #1}}{\\@nameuse{R@#1}}}"]
    for k in sorted(V):
        lines.append(f"\\@namedef{{R@{k}}}{{{V[k]}}}")
    lines.append("\\makeatother")
    write("numbers.tex", "\n".join(lines) + "\n")
    print(f"wrote {len(os.listdir(TAB))} files to {TAB}, 3 figures, {len(V)} numbers")


if __name__ == "__main__":
    main()
